### ISSUE TITLE
Easily accessible Release note for new version or updates

### ISSUE THREAD

**Issue by jsinh** [Topshelf/Topshelf#168]
I am using Topshelf for most of my official and non-official works that I do. We majorly rely upon Topshelf for all windows service we create now. Thanks for making it awesome to use :)

One thing as a consumer that I would like to request is easily accessible Release notes for each new version you push for all users. This will help us to understand what is changed, what will break, what has to be done differently, what is improved, what you have offered new, blah blah.

Any thoughts or directions?

**Comment by olivier-spinelli** [comment]
My humble 2 cents: the Github release tag is far better since it can be edited at any time: any post-release information that pops (like undiscovered incompatibilities at release time or security issues) can efficiently be "distributed" to consumers.

For me, the NuSpec "ReleaseNotes" should actually be "ReleaseNotesUrl", ie. https://github.com/Topshelf/Topshelf/releases/tag/v4.0.0  is the place to go...
