### ISSUE TITLE
#Wishlist - IOC / Windsor support for custom loggers

### ISSUE THREAD

**Issue by osudude** [Topshelf/Topshelf#200]
We have our own logging framework that logs to Hipchat, sql, etc.  To currently integrate with TopShelf, we have to:

1. Write custom HostLoggerConfigurator
2. Write custom LogWriter
3. Write custom LogWriterFactory
4. Wire up custom HostLoggerConfigurator with HostLogger.UseLogger

It would be cool if TopShelf had some IOC support that could check for a custom HostLoggerConfigurator and if found just use the version exposed by IOC.

**Comment by drusellers** [comment]
At this point that is your hook into the topshelf logs. I don't imagine we would add IoC to the mix because it adds a large burden of supporting containers as well as Topshelf usually has you create your IoC in the start method which is after logging has been created. If that makes sense please feel free to close the issue, or lets talk about some other options. :)

**Comment by osudude** [comment]
Fair enough.  In lieu of full blown IOC support, it would be nice if the logging framework would honor IDisposable on ILogger instances so my code can release the instance managed by IOC.  Since the logging framework does not honor IDisposable on ILogger instances, I have to set my logger instances  to Singleton life style :(

**Comment by drusellers** [comment]
We don't have an `ILogger` interface to call Dispose on. So I assume you are referencing your Logger class. `LogWriterFactory` does have a `Shutdown` method that is called. Can you help me better understand your request? If I were to make a wild assumption, it would be that your logging is setup as a part of building out your container, which we advise you do in the start method so that you can restart the service without cycling the AppDomain. Because of that I would recommend you configure Logging before TS and then pass the configured instance into the container in the 'Start' method.

**Comment by osudude** [comment]
Doh!  My mistake.. It's not a TopShelf problem with IDisposable not being honored on ILogger.  It's a MassTransit issue.

**Comment by drusellers** [comment]
I will close this issue for now then. feel free to reopen. Also, please open an issue on MT about the logging thing and I'll se what I can do there.
