### ISSUE TITLE
HostConfigurator.UseLog4Net is repeately executed,leading to generate multi log files 

### ISSUE THREAD

**Issue by jello-chen** [Topshelf/Topshelf#269]

**Comment by jello-chen** [comment]
I use the SampleTopshelfService sample you provider,but I use the following RollingFileAppender instead of FileAppender.

```
<appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">
    <file value="Log/" />
    <rollingStyle value="Date" />
    <AppendToFile value="true" />
    <datePattern value="yyyyMMdd'.txt'" />
    <staticLogFileName value="false" />
    <layout type="log4net.Layout.PatternLayout">
      <ConversionPattern value="%date [%thread] %-5level %logger [%ndc] - %message%newline" />
    </layout>
  </appender>
~~~

In turn,Executint install,start,uninstall will leading to generate two log files

**Comment by phatboyg** [comment]
Well, that's likely how it's going to happen since the process creates a new file with each invocation when using the rolling file appender.

If you don't want to write to the log files during install/uninstall/start, don't initialize logging until you enter the service factory method - which is only called when the service is starting.

**Comment by jello-chen** [comment]
Ok,I got it,thanks.
