### ISSUE TITLE
Topshelf needs a feature to make sure the Current directory is the install directory and not the directory that windows services runs from. 

### ISSUE THREAD

**Issue by StewartScottRogers** [Topshelf/Topshelf#290]
Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);

**Comment by phatboyg** [comment]
Is that copied from here?

https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/WindowsServiceHost.cs#L58

I don't know what you're suggesting - the baseDirectory should be where the service was installed.

**Comment by alexdresko** [comment]
@phatboyg It's not, at least with the project I'm working on (ASP.NET Core + Full framework). 

For example, the following line works fine outside of Topshelf: `env.ConfigureNLog("nlog.config");`. In this case, `nlog.config` is found in the correct location. However, when running the same application under Topshelf, a `FileNotFoundException` is thrown because it's looking for `'C:\WINDOWS\system32\nlog.config'`. 

I managed to resolve that particular problem by changing the line to `env.ConfigureNLog(Path.Combine(Directory.GetCurrentDirectory(), "nlog.config"));`, but I'm running into other path related issues all over my application.

**Comment by valeriob** [comment]
I had the same problem if you try to access the path from the constructor of your service class (the one that extends ServiceControl, if you try inside the start method, it works as expected.
