### ISSUE TITLE
Having declared a cmd line arg, and using 'install start' together ignores the 'install' and just tries to start.

### ISSUE THREAD

**Issue by jbuedel** [Topshelf/Topshelf#305]
Given my topshelf exe called `shelf.exe`, that is _not currently installed_ (nor installed before any of my examples that follow), and created exactly from the sample code at https://topshelf.readthedocs.io/en/latest/configuration/quickstart.html, if I run
`shelf.exe install`
my service is installed, but not started. If I run
`shelf.exe start` 
a reasonable error is given saying it's not installed. If I run
`shelf.exe install start` 
my service is installed and started immediately.

That's all good, and what I would expect. If I add the code 
```
            string PlayerPianoSourceDirectory = null;
            x.AddCommandLineDefinition("playerpiano", cla => PlayerPianoSourceDirectory = cla);
            x.ApplyCommandLine();
```
to my Main (`x` is the `HostConfigurator`) and then run
`shelf.exe install start`
I get an error saying the service is not installed. 

I expected it to install the service and start automatically. Note that I am not even using the parameter I've defined. Simply the additional declaration of it triggers the problem. If I use the parameter by itself, like:
`shelf.exe -playerpiano:c:\temp`
my service is launched in console mode and my parameter is used, as expected. If I run `shelf.exe install` or `shelf.exe start`, they continue to work as expected. 

It seems the combination of having defined a custom cmd line arg with using the dual `install start` syntax triggers the issue.
Thanks,
Josh

**Comment by TravisTheTechie** [comment]
So I'm not sure the issue here without seeing a stack, but you're going to end up having a bad time. Custom command line items don't really work well once the service is installed. You should fall back on using configuration. 

https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L125-L139

As you see, the process needs that configuration applied every time it's executed. We include a few items in the image path of the service, but custom command line arguments are not included. There's a lot of reasons for that, but mostly boils down to we really shouldn't have this feature at all because it's confusing and hard to use.

**Comment by jbuedel** [comment]
I'm not getting an exception, nor is the issue about receiving my cmd line param after install.  The issue is that _simply defining_ a custom parameter (*not* even using it) causes the built in parameters  of `install start` to behave differently. "Differently" meaning the install step does not occur.
