### ISSUE TITLE
Topshelf keeps waiting for service start that already crashed

### ISSUE THREAD

**Issue by ichaynikov** [Topshelf/Topshelf#309]
I try to run a service using HostFactory.Run and topshelf keeps waiting for started service state even service has already been crashed with an exception during startup.
If service has started succesfully topshelf reports that service is started.

Is it possible to detect service crashing and report failed result code without waiting for a long?

Topshelf v3.3.154.0, .NET Framework v4.0.30319.42000

**Comment by TravisTheTechie** [comment]
Where is the service crashing? Do you have a stack trace indicating the handlers that is throwing? Or is it outside of the Topshelf lifecycle?

**Comment by uPLtraI1jCfiegGKB285** [comment]
Hey, I'm having the same problem. 

This seems to be due to `sc.WaitForStatus(ServiceControllerStatus.Running, startTimeOut);` in this file: https://github.com/Topshelf/Topshelf/blob/1ecd70e130e73fa9e958f506a493319523e660ff/src/Topshelf/Runtime/Windows/WindowsHostEnvironment.cs

Running as '&lt;executable&gt; start'

Either an exception or returning false doesn't stop this timeout and the executable will only exit once timeout has occurred. Debug shows that all threads are dead except for the one in WaitForStatus.

Is it possible to instead link the timeout to RequestAdditionalTime? And on wake up due to timeout check if additional time has been requested?

Alternatively check states more carefully, implementing WaitForStatus in topshelf by polling Status, and not require any topshelf timeout be set?

            var exitCode = HostFactory.Run(x =>
            {
                x.UseLog4Net();
                x.RunAsLocalSystem();
                x.SetDescription("");
                x.SetDisplayName(cs.Config.ServiceName);
                x.SetServiceName(cs.Config.ServiceName);
                x.SetStartTimeout(TimeSpan.FromMinutes(5));
                x.Service<Service>(s =>
                {
                    s.ConstructUsing(_ => new Service());
                    s.WhenStarted((service, hostControl) => 
                    {
                        //throw new Exception("what?");
                        return false;
                    });
                    s.WhenStopped(service => {});
                });
            });
            if (exitCode == TopshelfExitCode.Ok)
                log.Info("Exiting with success code");
            else
                log.Error($"Exiting with failure code: {exitCode}");

**Comment by krystian-axence** [comment]
Problem is not a Topshelf crashing, but unnecessary waiting for changing service status change (which in case of service start fails never happens).

When you call 'app.exe start', then this process instance calls Topshelf-StartService from 'src/Topshelf/Runtime/Windows/WindowsHostEnvironment.cs'.

        public void StartService(string serviceName, TimeSpan startTimeOut)
        {
...
                    sc.Start();  <- windows SCM will create new process to handle service (there is no error or an exception in this function). Now sc.Status should be ServiceControllerStatus.StartPending
                    sc.WaitForStatus(ServiceControllerStatus.Running, startTimeOut); <- now 'app.exe start' waits for new service process to change status to ServiceControllerStatus.Running, but it will never happens if the new service process will terminate/crash, because sc.Status will change to ServiceControllerStatus.Stopped - but sc.WaitForStatus continues to wait for ServiceControllerStatus.Running (but sc.Status is already ServiceControllerStatus.Stopped). 

Solution for this issue would be for example custom waiting (pooling with small sleep like 250ms) for service status change, and if service status changes to Stopped, then do not wait anymore for Running (because it won't change to that status). Of course total pooling time should be maxiumum up to startTimeOut.

**Comment by PeterEeg** [comment]
I'm having the same issue. It is highly inconvenient, I would call it a bug.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
