### ISSUE TITLE
[Question] Custom Command Line Options

### ISSUE THREAD

**Issue by ssta604** [Topshelf/Topshelf#330]
Why aren't custom command line options added to the image path?   I would really like to pass options like -port:4000, etc.

**Comment by chrkon** [comment]
I would like to have this feature, too. 
For my use case I have to start four different instances of my service. Each will listen on a different TCP port. 

At the moment I use the _InstanceName_ as workaround. I put the port number into the Instance name during install and parse it when the service starts. 

`myService.exe -install -instance "20032"  // after start my service is listening on port 20032`

This workaround has the positive effect, that the description fo the service shows the used port automatically.

**Comment by ChrisRichner** [comment]
You can add your custom switches and arguments.

```
HostFactory.Run(x =>
{
     x.AddCommandLineDefinition("port", (p) => o.ToString());
     x.AddCommandLineSwitch("ssl", (b) => b.ToString());
}
```

**Comment by ssta604** [comment]
Thank you Chris but this isn't the issue.  The problem is I want to pass some additional parameters to the service at startup.

The only way I can see to do this is by persisting the option to a file or the registry and rereading them at startup.  This is a bit of a hassle depending on the security context of the service.

My thinking is it would be much easier to persist the parameters as part of the image path.   A switch on CommandLineX controlling this behavior would be awesome.

**Comment by jcoutch** [comment]
Just assign the value to a variable, and pass it in the service's constructor.  Here's an example.

```
public class Program
{
	public static int Main(string[] args)
	{
		var _port = 0;
		
		return (int)HostFactory.Run(x =>
		{
			x.AddCommandLineDefinition("port", port => _port = int.Parse(port));
			
			x.Service<MyService>(s =>
			{
				s.WhenStarted(service => service.Start(_port));
				s.WhenStopped(service => service.Stop());
			});

			x.RunAsLocalSystem();

			x.SetDescription("A service with run-time parameters");
			x.SetDisplayName("Super awesome service");
			x.SetServiceName("SuperAwesomeService");
		});
	}
}

public class MyService
{
	public bool Start(int port)
	{
		Console.WriteLine("This is my port: " + port);
		
		return true;
	}

	public void Stop()
	{
	}
}
```

**Comment by ssta604** [comment]
Thanks jcoutch for the suggestion.   This is actually how I pass the port.   It won't help when the service is restarted. The problem is with persisting the information.

**Comment by ssta604** [comment]
HostConfigurator.AddCommandLineDefinition("port", port => _port = int.Parse(port), true);

**Comment by jcoutch** [comment]
The problem is that when a service is restarted, Windows stops the service, terminates the process, then restarts the process.  So persisting the settings in memory during a service restart is not an option.

On service installation, you could write a config file specific to that instance.  In this (very crude) example, I'm using FluentCommandLineParser to parse the port number, save it out to a config file during BeforeInstall, and then read it when the service is constructed.  I'm using the service name as the config file name, since TopShelf appends the instance name on it (i.e. `SuperAwesomeService$MyInstanceName`).  I think this may answer #333 too:

```
public class Program
{
    public static int Main(string[] args)
    {
        // Holds the value for BeforeInstall
        var port = 0;

        // Parses the command line for the instance parameter
        var parser = new FluentCommandLineParser();
        parser.Setup<int>("port")
            .Callback(val => port = val);
        parser.Parse(args);

        return (int)HostFactory.Run(x =>
        {
            x.UseNinject();
            x.AddCommandLineDefinition("port", value => { }); // Dummy command line definition
            x.BeforeInstall(y => PreInstall(y, port));
            x.Service<MyService>(s =>
            {
                s.ConstructUsing(settings => new MyService(settings.ServiceName));
                s.WhenStarted(service => service.Start());
                s.WhenStopped(service => service.Stop());
            });

            x.SetDescription("A service with run-time parameters");
            x.SetDisplayName("Super awesome service");
            x.SetServiceName("SuperAwesomeService");
        });
    }

    public static void PreInstall(InstallHostSettings installHostSettings, int port)
    {
        if (string.Equals(installHostSettings.InstanceName, string.Empty))
            throw new Exception("Hey!  You need to pass /instance before installing!");

        // Write port out to an instance-based file:
        using (var sw = new StreamWriter($"{installHostSettings.ServiceName}.config"))
        {
            sw.WriteLine(port);
        }
    }
}

public class MyService
{
    private int Port { get; set; }

    public MyService(string serviceName)
    {
        using (var sr = new StreamReader($"{serviceName}.config"))
        {
            Port = int.Parse(sr.ReadLine());
        }
    }

    public void Start()
    {
        Console.WriteLine($"Yo!  My port be {Port}");
    }

    public void Stop()
    {
    }
}
```

**Comment by TravisTheTechie** [comment]
Yeah, so what happens if you run the command line again with different command line arguments than are on the image path? What happens if you include command line arguments with the start command (they would be ignored, image path would be used)? The reason you can't do this is I don't have a solution for the complexity around managing this. I've almost ripped out the ability to do it all a couple times but too many people depend on it :/.

**Comment by ssta604** [comment]
I understand your frustration :(

I think appropriatly flagged parameters should be persited to the image path via the install verb.   These parameters should be ignored when using the start verb.

**Comment by TravisTheTechie** [comment]
Yeah, I mostly agree with you. Start should ignore the parameters... but it's not obvious and we don't have systems in place to signal that. I think it's possible, just not simple enough that I feel like I can easily deliver something that won't create a ton of support headaches for me. 

I'm open to making sure we have a way to expose the option to edit the image path when it's needed. I'm not sure this functionality would be enabled by default, but we get this request enough that having an enabler maker sense. I'm not 100% sure off the top of my head what it might look like, but if it's of interest I'm happy to explore some ideas with you for a bit.

**Comment by ssta604** [comment]
Exposing a method to edit the image path might help.

Another idea I had is maybe proving some sort of setting persistence mechism baked into topshelf.         I'm not really sure where the best place to persist the values would be.  In the service reg. entry?

I know I can do this myself but it would be nice if I didn't have to worry about ACLs, etc. in HKEYLM.

**Comment by ssta604** [comment]
Exposing a method to edit the image path might help.

Another idea I had is maybe proving some sort of setting persistence mechism baked into topshelf.         I'm not really sure where the best place to persist the values would be.  In the service reg. entry?

I know I can do this myself but it would be nice if I didn't have to worry about ACLs, etc. in HKLM.

**Comment by thoemmi** [comment]
Hi, I have the same requirement, passing additional parameters to the service.

My (simple) proposal is to add a property to `InstallHostSettings`, either a `string` or a `NameValueCollection` (or `IDictionary<string, string>`, is preferred). Following @jcoutch example, depending on the type you could then call
```c#
x.BeforeInstall(ihs => ihs.AdditionalCommandLine = $"/port={_port}");
```
or
```c#
x.BeforeInstall(ihs => ihs.AdditionalCommandLineArguments.Add("port", _port.ToString());
```
respectively.

[`HostServiceInstaller.CreateHostInstaller`](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Runtime/Windows/HostServiceInstaller.cs#L132-L146) should add these additional parameters to the `arguments`.

If you think this approach is viable, I would be happy to create a PR.

**Comment by goldsam** [comment]
Being able to parameterize a service instance is a pretty requirement. If I "install" a second time with different parameters, I would expect them to simply overwrite the old parameters as most tools do. For example, `passwd` in unix update your password by overwriting the previous password. I'm really not understanding what the challenge is.

**Comment by albertoVieiraNeto** [comment]
i also felt the need for this feature, currently i will have a service run multiple instances, the way i solved isnt all that pretty. i'm using a configuration file, it would be alot easier if i could simply use a command line argument to configure it.

**Comment by lauxjpn** [comment]
> Being able to parameterize a service instance is a pretty requirement for a lot of software. If I "install" a second time with different parameters, I would expect them to simply overwrite the old parameters as most tools do.

That should be the way to implement this. I would also suggest just to add all unrecognized parameters from the `service install` to the `ImagePath`. It's the simplest solution.

As long as this feature is not implemented, the usage scenarios for Topshelf are limited.

**Comment by thoemmi** [comment]
Three years ago I've published a pull request, which unfortunately was rejected: #356 

However, in the comments you can find a workaround: https://github.com/Topshelf/Topshelf/pull/356#issuecomment-282596980

**Comment by lauxjpn** [comment]
> However, in the comments you can find a workaround: [#356 (comment)](https://github.com/Topshelf/Topshelf/pull/356#issuecomment-282596980)

Thanks for linking back to that.

> I would also suggest just to add all unrecognized/custom parameters from `service install` to the `ImagePath`. It's the simplest solution and will work for everybody. To make this more explicit, they can be made part of the output messages when installing the service.

@TravisTheTechie I think we should discuss this again, now that it is 3 years later.

**Comment by lauxjpn** [comment]
> I would also suggest just to add all unrecognized/custom parameters from `service install` to the `ImagePath`. It's the simplest solution and will work for everybody. To make this more explicit, they can be made part of the output messages when installing the service.

@TravisTheTechie I would really like to discuss this approach with you or whoever currently is has decision making authority for this repo.
Do you have any reservations about implementing support for this feature in this way (this would be a non-breaking change)? If so, what are they?

There seems to be very little going on for this repo from regarding development, issue support or PR support.

**Comment by TravisTheTechie** [comment]
@lauxjpn I think there are still some challenges with passing everything to the `ImagePath` from a usability standpoint. There's no way to express or query that as it stands and would cause a number of tickets to help folks debug unless there was a comprehensive approach to modifying the image path. These are solvable problems but turns a "simple" PR into a much more comprehensive approach and thought about the existing & new workflows needed. We're kinda abusing `ImagePath` and it shows. The "workaround" of configuration has been preferred because visibility and changing those values are more obvious. Acknowledging there are trade-offs all around here. 

If I were to approach this, I would make sure I addressed the following...

1. After running `install`, how can I see what parameters are on the image path during start?
1. During an `uninstall`/`install` round, how do I ensure I can tell what's changed?
1. What's the impact if Topshelf adds new parameters and suddenly things break? Is there a mitigation? [I can think of a few, but haven't dove into trade-offs]
1. What side effects are there for attempting to add the parameters to other calls; does it only work for install? What if I wanted to start with changed parameters? Or how would we message it to users who tried that?
1. What documentation needs updated to reflect whatever changes are needed. 

Given all that, I haven't touched Topshelf code in years, it's mostly been @phatboyg and I don't even know if I still have rights. So I think you'll need to convince Chris. My opinions are of limited value. From another perspective though, Topshelf API is reasonably composable -- if you can't compose an extension to do this for your use case then talking about what extension points you need to make it happen might be a worthwhile discussion.

**Comment by lauxjpn** [comment]
@TravisTheTechie Thanks for taking the time about this issue! I will discuss this further with @phatboyg then, but I will address your points here, because they are valid concerns.

First of all, I see two possible ways of going here about parameters in general. We can either just add all custom parameters to the image path when running `install`, or just the ones that were explicitly defined (using `ApplyCommandLineOptions()`). The latter approach should be simpler, better controllable and has a smaller project impact, because the whole infrastructure to suppport that already exists. So let's assume the second approach here.

> After running install, how can I see what parameters are on the image path during start?

Topshelf currently does not provide any command line argument output, unless you misspell something. This is true for *all* verbs (including `run`) and not just `start`.

Users are able to take a look at the used image path in the `services.msc` snap-in, using the command line or PowerShell, or of course using the registry. This is how Windows services have always been, so I consider this expected.

We could of course think about logging the parameters that are being used to run the service. We could implement this just for `run`, because `start` just starts the service that then executes in `run` mode.

> During an uninstall/install round, how do I ensure I can tell what's changed?

I am not sure I fully understand the question. If I uninstall a service, all its values (including the image path) are removed from the registry. When I then install it again, whatever I provide as parameters on the command line is added to the registry again. I know what I changed, because I am the one who changed it.

> What's the impact if Topshelf adds new parameters and suddenly things break? Is there a mitigation? [I can think of a few, but haven't dove into trade-offs]

This is a common scenario in basically all software projects. If we add new parameters, then a colission with a custom parameter somebody is already using is theoretically possible, if somebody updates to the new Topshelf version.

However, this is just part of the update and versioning process. If e.g. SemVer is used, then I know by looking at the new Version number, if breaking changes are expected or not. Also, if I update something, I need to assume that something could break, so I need to retest it.

In practice, this is unlikely to be a huge issue, because Topshelf has a very specific scope that it already covers to a large degree.

BTW, this issue already currently exists for the `run` mode, so whatever is done or not done for `run` just applies here as well.

> What side effects are there for attempting to add the parameters to other calls; does it only work for install? What if I wanted to start with changed parameters? Or how would we message it to users who tried that?

We should throw if invalid parameters are being used for the current verb. If custom parameters are used for the `start` command, then an exception should be thrown.

It makes sense to not just tell the user, that the parameter was wrong, but if it indeed is a custom parameter, that the parameter can only be set at installation time for services or provided together with the `run` verb when executing the app add-hoc without installing.

Of course we could just ignore anything we don't recognize, but being explicit is usually preferable and significantly cuts down potential troubleshooting time a user encounter when doing the wrong thing.

The custom parameters should only be valid for the `run` and `install` commands. If a user wants to change the custom parameters for an already installed service, the Topshelf supported way to do this would be to reinstall the service.

> What documentation needs updated to reflect whatever changes are needed.

I will update the docs occordingly to the changes (i.e. additions) in functionality. This would include [Topshelf Command-Line Reference](http://docs.topshelf-project.com/en/latest/overview/commandline.html) and [Topshelf Key Concepts: What about command-line arguments](http://docs.topshelf-project.com/en/latest/overview/faq.html#what-about-command-line-arguments). While I am at it, I will also extend the [Quickstart](http://docs.topshelf-project.com/en/latest/configuration/quickstart.html) article, so that it includes a custom parameter and the command lines to run, install and start the service.

> if you can't compose an extension to do this for your use case then talking about what extension points you need to make it happen might be a worthwhile discussion.

I agree that Topshelf's architecture is highly abstracted and composable. But it took me some time to figure out, that this scenario is not supported out-of-the-box and forced me to dive deeper into the Topshelf code. Because the whole point of Topshelf is to make implementing (and debugging) Windows services more comfortable/simpler/faster, so I am convinced that this issue needs to be addressed as part of the main package.

**Comment by phatboyg** [comment]
I'll take a look at a well-crafted PR that adds this capability. For those developers still using Windows, I know Topshelf has been a staple for years. I've moved on to .NET Core and Linux, so I no longer reach for Topshelf as the Generic Host from .NET Core is easier to support and socialize from a consistency/standards perspective.

**Comment by lauxjpn** [comment]
> the Generic Host from .NET Core is easier to support

That's a good point.

> I'll take a look at a well-crafted PR that adds this capability.

I will provide one over the next two weeks or so.

**Comment by ristogod** [comment]
Did this never happen? This is vital functionality that should exist by default. I struggle to understand the difficulty?

**Comment by phatboyg** [comment]
Topshelf is no longer supported. Use the generic host instead.
