### ISSUE TITLE
Question: How to add a custom action like install,uninstall,help?

### ISSUE THREAD

**Issue by ChrisRichner** [Topshelf/Topshelf#333]
I'm well aware that one can add command line switches and arguments. 

I would like to add a custom action which then gets invoked like those found for .BeforeInstall() or .AfterInstall().

In my use case I need to extend the given CLI interface like start, stop, install, uninstall with a custom action / command.

This command should let me invoke code inside the HostFactroy.Run() comparable to the .BeforeInstall(settings) extension method. Because I need to know if the user specified an instance name etc.

Thanks!

**Comment by jcoutch** [comment]
Hey @ChrisRichner, I think my answer above to Issue 330 may help you.

**Comment by jcoutch** [comment]
If you just need to know before service startup/install if an instance name was provided, HostSettings and InstallHostSettings provides the InstanceName property.  You can use `s.ConstructUsing(settings => new MyService(settings.InstanceName));` to pass the instance name to your service constructor (or just add a HostSettings parameter to your constructor if using dependency injection), and then use the overload of `WhenStarted` that provides HostControl to stop your service if an instance name is required.

Looking through Topshelf's source code, you wouldn't be able to know the instance name within HostFactory.Run itself, since you aren't guaranteed that the command line has been parsed until your service is constructed (which passes along the HostSettings object.)  If it's an absolute must that you know in HostFactory.Run, just use a command line parser like FluentCommandLineParser and check for an instance parameter.

**Comment by ChrisRichner** [comment]
Thank you! I already have a bunch of regular command line arguments in use which are forwarded to the service control class.

What I like to achieve is so to have a custom action / host like install or uninstall action does have. 

The service itself does not start and the console exits after the custom logic ran. Analog what happens when you call help, install or uninstall.

I want to place the custom action user code inside a .MyCustomAction(settings => ...) HostConfiguration extension method.

Would be awesome to have a sample showing how to do this, right?

**Comment by TravisTheTechie** [comment]
So help me understand what you're trying to do here a bit more. If I understand it correctly, you want to be able to call `install` with an additional `update-something` command + parameters? Would this only happen during a install/uninstall? What would you expect to happen during stop/stop?

**Comment by ChrisRichner** [comment]
Topshelf has built-in actions install, uninstall and help. When these actions are called the service implementation class itself does not get instantiated and started. Instead the install, uninstall or help logic gets executed and the process exits. During the execution of install the user code in .BeforeInstall(settings0>...) gets called. This way you can execute custom code during install phase.

I would like to have the same behavior for a completely custom action.

> myservice.exe ssl [-instance "I01"]

now when this custom actions run it should execute the Ssl() extension method and exit the process.

`HostConfiguration.Ssl(settings => ...);`

This way the ssl command can do it's job like the install / uninstall actions do their jobs by running their logic and let the user execute some additional custom code.

Hope this helps to give you an idea of what I'm trying to accomplish

Thanks

**Comment by TravisTheTechie** [comment]
I see what you're talking about now. So it's been a while since I've dug into this but I'll try to point you into the right direction here... 

* Create a custom `Host`, e.g. [StopHost](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Hosts/StopHost.cs) or [HelpHost](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Hosts/HelpHost.cs)
* Create a host builder, e.g. [HelpBuilder](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/Builders/HelpBuilder.cs)
* Create a configurator, e.g. [SystemOnlyHelpHostConfigurator](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/HostConfigurators/SystemOnlyHelpHostConfigurator.cs)
* And a Option to tie it together, e.g. [HelpOption](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf/Configuration/Options/HelpOption.cs)

And I think everything gets bound together automatically. I might be missing a step since this is me thinking about code that hasn't been touched in years. But I think it would walk you down the right path to start. A worst, you need a method to pass into your host configurator to bind the option. 

If you feel like you get this working and have an example, we'd be happy to include a sample in the docs. It hasn't yet been something someone has asked for but doesn't mean it isn't wanted.

**Comment by supermankelly** [comment]
This sound like what I need. I have a program which runs a specific class based on the argument passed. 

```
myapp.exe arg1      (runs class1 and exits)
myapp.exe arg2      (runs vlass2 and exits)
myapp.exe loopall   (this would be the Topshelf service - myapp.exe start)
```

But I still want the ability to run each class function independently as it does now.
