### ISSUE TITLE
HostControl.Stop(TopshelfExitCode.UnhandledServiceException) does not trigger recovery options

### ISSUE THREAD

**Issue by taniaengel** [Topshelf/Topshelf#479]
I have the following code to run my Topshelf hosted services.
            HostFactory.Run(conf =>
            {
                conf.Service<TService>(svcConf =>
                {
                    svcConf.ConstructUsing(name => new TService());
                    svcConf.WhenStarted((si, hostControl) =>
                    {
                        return si.Start(hostControl);
                    });
                   ...
                }).OnException(ex =>
                {
                    Log.Error(ex, $"unhandled: {ex?.Message}");
                });
...

My Start will return true/false depending on how start goes and returns quickly so the windows service goes running. Then what I want to do is have the Start trigger Run with Task.Run(async...). As we know, that causes unhandled exceptions during run to fall on silent ears. So, I decided inside the async to catch all exceptions, log, and then invoke hostControl.Stop(TopshelfExitCode.UnhandledServiceException). This worked great to stop the host service and it generated a Windows System event log Error strangely stating : " The XXX service terminated with the following error: Not enough storage is available to process this command".  However, it **did not trigger the recovery options**. I think the implementation of WindowsHostService Stop(TopshelExitCode) should do what is required to trigger the Windows service recovery options.

Just as a side note. I also implemented the run using new Thread(...).Start() and the unhandled exception did throw to TopShelf, it did stop the service, and it did trigger the Windows recovery options to restart the service.

**Comment by taniaengel** [comment]
Also, my original test was with recovery options set in windows. I also tested setting the recovery options on the Topshelf HostConfigurator as shown below. Using hostControl.Stop(exitcode) still didn't trigger the recovery options. 
  conf.EnableServiceRecovery(r =>
            {
                r.RestartService(1);
                r.RestartService(1);
                r.RestartService(2);
                r.OnCrashOnly();
                r.SetResetPeriod(0);
            });

**Comment by alimhabib** [comment]
> Also, my original test was with recovery options set in windows. I also tested setting the recovery options on the Topshelf HostConfigurator as shown below. Using hostControl.Stop(exitcode) still didn't trigger the recovery options.
> conf.EnableServiceRecovery(r =>
> {
> r.RestartService(1);
> r.RestartService(1);
> r.RestartService(2);
> r.OnCrashOnly();
> r.SetResetPeriod(0);
> });

I tried 

`                x.StartAutomatically(); // I added it as a precaution,  but the script call start 
                x.RunAsLocalService();
                x.OnException(exception =>
                {
                   Log(exception, exception.Message);                   
                });

                x.SetDescription(_serviceDescription);
                x.SetDisplayName(_serviceDisplayName);
                x.SetServiceName(_serviceName);

                // Recovery of the service 
                x.EnableServiceRecovery(r =>
                {
                    Log("A service Recovery was called");
                    r.RestartService(0);
                    r.SetResetPeriod(1);
                });`

and it worked for me , maybe this can help

**Comment by kbandrew** [comment]
Any update on this?

We are facing the same issue.

**Comment by razor2651** [comment]
> Any update on this?
> 
> We are facing the same issue.



we also faced this problem
but initially did not use any recoveryOptions

first of all, we configured our service from a ps script
`sc failure <name> reset = <seconds> actions = restart / <ms> / restart / <ms> / restart / <ms>`
which should be equivalent to such code
```
conf.EnableServiceRecovery (r =>
{
    r.RestartService (...);
    r.RestartService (...);
    r.RestartService (...);
    r.OnCrashOnly ();
    r.SetResetPeriod (...);
});
```
but the configuration from the code is not very suitable for us

and then I started to experiment
my service looked something like this

```
public bool Start([NotNull] HostControl hostControl)
{
    <...>
    var container = BuildContainer();
    service = container.Resolve<T>();
    runTask = Task.Run(
        () => 
        {
            try
            {
                <...>
                await service.RunAsync(token).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
            }
            catch (Exception e)
            {
                log.Fatal("SERVICE FAILED", e);
            }
        });
    return true;
}


public bool Stop([NotNull] HostControl hostControl)
{
    TerminateConnections()
    <...>
    return true;
}
```

we needed to ensure that the service automatically restarted in the event of a fatal error
1) we made the `RunAsync` method such that it raises a `StackOverflowException` (so that we cannot catch the exception)
in this case, the service crashed with error 1
and `eventViewer` got the correct event by which it was decided to restart the service

2) then we returned `RunAsync` as it was, but in the `Main` method we started to return 1
the result was the same

3) topshelf on the `HostFactory.Run` method allows you to get exitCode, which can be passed to `hostControl.Stop (<exitCode>)`
we returned the received error code in the `Main` method and returned it from the application, as a result, the wrong event fell on `eventViewer`, according to which the service could not restart

4) we repeated the same thing, but in the `Main` method we returned code 1 from the program, not the exitCode that was received from the `HostFactory.Run` method
even in this case, an incorrect event was generated and the service did not restart

we tried to figure out the topshelf code and understand why this is happening but did not find the answer

as a hack, it was decided to process the error in the Start method, call Stop, and then do `Environment.Exit (1)`

in the end, it solved our problem, the code now looked something like this

```
public bool Start([NotNull] HostControl hostControl)
{
    <...>
    var container = BuildContainer();
    service = container.Resolve<T>();
    runTask = Task.Run(
        () => 
        {
            try
            {
                <...>
                await service.RunAsync(token).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
            }
            catch (Exception e)
            {
                log.Fatal("SERVICE FAILED", e);
                serviceReturnCode = TopshelfExitCode.AbnormalExit;
            }
        });
    return true;
}


public bool Stop([NotNull] HostControl hostControl)
{
    TerminateConnections()
    <...>
    if (serviceReturnCode == TopshelfExitCode.AbnormalExit)
    {
        Environment.Exit(1);
    }
    return true;
}
```

we are understand that this is a dirty hack,
but I would like to understand why topshelf generates an incorrect event when the service is crashed (when exitCode not equal 0, and we call hostControl.Stop( `<exitCode>` )
anybody can help?

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
