### ISSUE TITLE
RunAsPrompt() doesn't validate the login

### ISSUE THREAD

**Issue by rhuanbarreto** [Topshelf/Topshelf#482]
The dialog for asking the user and password during service installation doesn't validate if the login is right or wrong. Only validate if the passwords are the same.

Is that behaviour intentional?

**Comment by deinman** [comment]
As far as I can tell that's actually a behavior of the Windows services.

Steps to reproduce:

1. Open Services.msc
2. Right click on a service and select Properties
3. Choose "Log On" tab at the top
4. Enter a valid account
5. Enter invalid password and confirm using the same password

Windows seems to accept it, regardless of whether it's the correct password.

On service startup then Windows will complain about startup failure due to invalid logon.

**Comment by rhuanbarreto** [comment]
But could it be some improvement for the library? I would love to have this, but I don't have the knowledge for making this and put a PR on this repo.

**Comment by bruceburge** [comment]
> 
> 
> But could it be some improvement for the library? I would love to have this, but I don't have the knowledge for making this and put a PR on this repo.

The prompt validation is to make sure you are entering the same password, the password is not passed to windows authentication, so that is why it doesn't check, and it wouldn't be something topshelf could do directly.

**Comment by rhuanbarreto** [comment]
Fine. I will close this issue as it's a feature that won't be done.
